# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgressUI(object):
    def setupUi(self, ProgressUI):
        ProgressUI.setObjectName("ProgressUI")
        ProgressUI.resize(480, 640)
        ProgressUI.setStyleSheet("background-color:rgb(32,32,32);")
        self.centralwidget = QtWidgets.QWidget(ProgressUI)
        self.centralwidget.setObjectName("centralwidget")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(10, 60, 461, 191))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.info_label.setFont(font)
        self.info_label.setAutoFillBackground(False)
        self.info_label.setStyleSheet("color: white;")
        self.info_label.setText("")
        self.info_label.setTextFormat(QtCore.Qt.AutoText)
        self.info_label.setAlignment(QtCore.Qt.AlignCenter)
        self.info_label.setWordWrap(True)
        self.info_label.setOpenExternalLinks(False)
        self.info_label.setObjectName("info_label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 280, 441, 31))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color:  rgb(84, 84, 84);\n"
"    color: rgb(200, 200, 200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.523, x2:1, y2:0.534091, stop:0 rgba(51, 51, 51, 255), stop:1 rgba(221, 24, 24, 255))\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        ProgressUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProgressUI)
        QtCore.QMetaObject.connectSlotsByName(ProgressUI)

    def retranslateUi(self, ProgressUI):
        _translate = QtCore.QCoreApplication.translate
        ProgressUI.setWindowTitle(_translate("ProgressUI", "buX Scrapper"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProgressUI = QtWidgets.QMainWindow()
    ui = Ui_ProgressUI()
    ui.setupUi(ProgressUI)
    ProgressUI.show()
    sys.exit(app.exec_())
